server:
  port: ${SRV_PORT}

spring:
  datasource:
    url: jdbc:h2:mem:${DB_NAME}
    driver-class-name: org.h2.Driver
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    hibernate:
      ddl-auto: update
